name: 'Automated version bump for internal monorepo'
description: 'Automated version bump for internal monorepo'
inputs:
  tag-format:
    description: 'Tag format'
    required: true
    default: 'v'
  version-file:
    description: 'The path to the version file'
    required: false
    default: None
outputs:
  version:
    description: 'Version'
runs:
  using: 'node20'
  main: 'dist/index.js'